CalmGuild/CalmBot

src/commands/socials.js
its literally just a link to linktree
=> feat: create socials command

src/events/message.js
1 in 10 thousand chance for @everyone, otherwise picks a random player to ping, but commented out
=> feat: add @someone back to discord

src/commands/eval.js
Added eval.js (evaluates inputted javascript code).
Only owner has access.
Responds with embed including input and output.
=> Eval.js Command for Bot Owner

README.md, src/commands/fact.js, src/commands/link.js, src/commands/trivia.js
Just a few minor tweaks to fact.js, link.js, trivia.js and README.md.
=> Basic Changes to Commands and README.md

README.md, src/commands/rps.js
- Added c!rps
- Uses embeds
- Reacts with 3 emoji's, which user has to choose from
- Once user chooses, bot will choose and will edit embed to display who won/lost/tied.
**Tested and working on latest CalmBot build!**
=> Rock-Paper-Scissors Fun Command!

src/commands/cheems.js, src/data/img/cheems.json
fixes #29 
it works the same as the other image commands
=> feat: add cheems command

README.md, src/commands/shutdown.js, src/commands/sleep.js, src/events/message.js
Changed the wording of shutdown related things.
Made it so the bot does not respond AT ALL to commands when sleeping
Switched shutdown to sleep
=> Change some wording | Switch c!shutdown --> c!sleep

src/client.js, src/commands/link.js, src/events/messageUpdate.js
=> fix: count-to-channel & syntax errors

src/commands/info/birthday.js
=> add bday cmd

src/client.js
**Help + Prefix Commands**: 
-> _**Help**_: Prints all current commands with categories and their descriptions. / Prints specific information on a specified command. _{c!help (command)}_
-> _**Prefix**_: Changes current guild prefix / Displays current prefix. _{c!prefix (prefix)}_
Closes #26
=> [+] Help Command, Prefix

src/commands/util/link.js, src/commands/util/suggest.js, src/data/calm/channels.json, src/requests/trivia.js
**Suggest Command**:
-> Make suggestion! Sends to suggestions channel.
=> [+] Suggestion Command

src/commands/util/userinfo.js
**Userinfo Command**:
-> Aliases: 'user', 'whois'
-> Usage: ${prefix}userinfo [id/mention]
=> [+] Userinfo Command

src/commands/fun/ship.js, src/commands/info/application.js, src/commands/info/birthday.js, src/commands/info/reqs.js, src/commands/info/roles.js, src/commands/info/socials.js, src/commands/info/trial.js, src/commands/info/vouch.js, src/commands/util/link.js, src/commands/util/suggest.js
=> Getting things ready for production

README.md
**README.md** updated to look cleaner and better
go read the read me file
=> [+] Updated README.md

src/commands/fun/8ball.js, src/commands/info/birthday.js
=> [+] LAST SECOND CHANGES

src/commands/fun/8ball.js, src/commands/info/birthday.js
OH GOD WE ARE ALL GOING TO DIE
=> ADD LATEST CHANGES INTO PRODUCTION

src/commands/fun/8ball.js
AAAAAAAAAAAH IM NOT FILLING THIS IN JUST CHANGED DESCRIPTION
SHUT UP
=> [+] CHANGED DESCRIPTION OF 8ball.JS

Procfile, package.json, src/commands/fun/ship.js, src/data/calm/channels.json
=> Production into Master

src/client.js
=> [+] Disabled Everyone Ping

src/commands/admin/lockdown.js, src/commands/admin/unlock.js, src/data/calm/channels.json
Support for the new channels that were added in calm.
=> Refactor lockdown and unlock.js and channels.json

src/commands/admin/abort.js, src/commands/util/poll.js, src/commands/util/suggest.js
**c!poll**
-> c!poll Is Miqhtie Cool? 
Reacts with Yes / No
=> [+] Poll Command + Minor Fixes

package.json, src/commands/util/emotesuggestion.js, src/data/calm/channels.json
=> [+] Emote Suggestion Command
